//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int account_id { get; set; }
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<short> active { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public int user_role { get; set; }
    
        public virtual user user { get; set; }
        public virtual user_role user_role1 { get; set; }
    }
}
