//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class airplane_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public airplane_type()
        {
            this.airplanes = new HashSet<airplane>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public int manufacture_id { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> wingspan { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<int> seat_number { get; set; }
        public Nullable<int> cruising_speed { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<airplane> airplanes { get; set; }
        public virtual manufacture manufacture { get; set; }
    }
}
