//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Flight_ManagerEntities : DbContext
    {
        public Flight_ManagerEntities()
            : base("name=Flight_ManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<airline> airlines { get; set; }
        public virtual DbSet<airplane> airplanes { get; set; }
        public virtual DbSet<airplane_type> airplane_type { get; set; }
        public virtual DbSet<airport> airports { get; set; }
        public virtual DbSet<assignment> assignments { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employee_position> employee_position { get; set; }
        public virtual DbSet<flight> flights { get; set; }
        public virtual DbSet<manufacture> manufactures { get; set; }
        public virtual DbSet<regulation> regulations { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<seat_class> seat_class { get; set; }
        public virtual DbSet<seat_type> seat_type { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<ticket_price> ticket_price { get; set; }
        public virtual DbSet<ticket_type> ticket_type { get; set; }
        public virtual DbSet<transit_airport> transit_airport { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
    }
}
