//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flight()
        {
            this.assignments = new HashSet<assignment>();
            this.seat_class = new HashSet<seat_class>();
            this.tickets = new HashSet<ticket>();
            this.ticket_price = new HashSet<ticket_price>();
            this.transit_airport = new HashSet<transit_airport>();
        }
    
        public string flight_id { get; set; }
        public string airplane_id { get; set; }
        public int schedule_id { get; set; }
        public Nullable<int> flight_time { get; set; }
        public System.DateTime departure_day { get; set; }
        public System.DateTime arrival_day { get; set; }
        public Nullable<int> number_of_empty_seats { get; set; }
    
        public virtual airplane airplane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignment> assignments { get; set; }
        public virtual schedule schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seat_class> seat_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket_price> ticket_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transit_airport> transit_airport { get; set; }
    }
}
