//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class regulation
    {
        public int regulations_id { get; set; }
        public Nullable<int> number_of_airports { get; set; }
        public Nullable<int> minimum_flight_time { get; set; }
        public Nullable<int> maximum_number_of_intermediate_airports { get; set; }
        public Nullable<int> minimum_estimated_time_of_the_stop { get; set; }
        public Nullable<int> maximum_estimated_time_of_the_stop { get; set; }
        public Nullable<int> ticket_sales_time { get; set; }
        public Nullable<int> ticket_booking_time { get; set; }
    }
}
