//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int ticket_id { get; set; }
        public string flight_id { get; set; }
        public int customer_id { get; set; }
        public string bill_id { get; set; }
        public Nullable<System.DateTime> booking_date { get; set; }
        public Nullable<int> ticket_type { get; set; }
        public int seat_id { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual customer customer { get; set; }
        public virtual flight flight { get; set; }
        public virtual seat seat { get; set; }
        public virtual ticket_type ticket_type1 { get; set; }
    }
}
