//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class transit_airport
    {
        public string transit_airport_id { get; set; }
        public string flight_id { get; set; }
        public Nullable<int> timing_point { get; set; }
        public Nullable<System.DateTime> arrival_day { get; set; }
        public string note { get; set; }
    
        public virtual airport airport { get; set; }
        public virtual flight flight { get; set; }
    }
}
